[project]
name = "catanytics"
version = "0.1.0"
description = "Analysis for Settlers of Catan"
readme = "README.md"
authors = [
    { name = "Mulmpages", email = "mulmpages@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
catanytics = "catanytics:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
